# Generated by Django 4.0.6 on 2022-07-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('name', models.CharField(max_length=35)),
                ('code', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('duration', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
    ]
